### ISSUE TITLE
JavaScript Program to calculate days left until next Ganeshotsav.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/JavaScript_Programs#6]

**Comment by pavankumarraju13** [comment]
@prasadsawant7  can you assign it to me?
 i have a doubt every year the date will be different right?

**Comment by prasadsawant7** [comment]
> @prasadsawant7 can you assign it to me? i have a doubt every year the date will be different right?

Hey @pavankumarraju13 i'll be creating another repo which will be named as Hacktoberfest-2022. You can contribute there.

**Comment by kaushal7208** [comment]
Hey assign me!

**Comment by pavankumarraju13** [comment]
@prasadsawant7 
yeah ok

**Comment by prasadsawant7** [comment]
> @prasadsawant7 yeah ok

I'm sorry this repo is for my friends who are new to open source, so, to teach them I have created it.

**Comment by prasadsawant7** [comment]
> Hey assign me!

sure.
