### ISSUE TITLE
JavaScript Program to convert temperatures to and from Celsius, Fahrenheit.

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/JavaScript_Programs#7]

**Comment by theadityaagnihotri** [comment]
can i work on it?

**Comment by prasadsawant7** [comment]
> can i work on it?

Stay tuned with me and I will invite you to my another repo which will be named as Hacktoberfest-2022. There you can contribute freely. I'm sorry this repo was for my college friends only, but I welcome you to my another repo.

**Comment by kaushal7208** [comment]
Hey assign me!

**Comment by prasadsawant7** [comment]
> Hey assign me!

sure.
