### ISSUE TITLE
JavaScript Program to get the website URL (loading page).

### ISSUE THREAD

**Issue by prasadsawant7** [prasadsawant7/JavaScript_Programs#8]

**Comment by snehildeep** [comment]
i will do it. Please assign me.

**Comment by snehildeep** [comment]
i have already done it . please merge it. Thank You.

**Comment by prasadsawant7** [comment]
> i have already done it . please merge it. Thank You.

Stay tuned with me and I will invite you to my another repo which will be named as Hacktoberfest-2022. There you can contribute freely. I'm sorry this repo was for my college friends only, but I welcome you to my another repo.

**Comment by kaushal7208** [comment]
Hey assign me!

**Comment by prasadsawant7** [comment]
> Hey assign me!

sure.
